Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -45,19 +45,27 @@ jobs:
           sudo apt-get autoremove
           sudo apt-get -f install
 
-      - name: Create /tmp/panel directory if it doesn't exist
+      - name: Create /tmp/panel directory
         run: mkdir -p /tmp/panel
 
       - name: Clone Pterodactyl Panel repository
         run: |
           git clone https://github.com/pterodactyl/panel.git /tmp/panel
 
-      - name: Check contents of /tmp/panel directory
-        run: ls -l /tmp/panel
+      - name: Navigate to Pterodactyl Panel directory
+        run: cd /tmp/panel
+
+      - name: Check if docker-compose.yml exists
+        run: |
+          if [ -f docker-compose.yml ]; then
+            echo "docker-compose.yml found."
+          else
+            echo "Error: docker-compose.yml not found."
+            exit 1
+          fi
 
       - name: Configure Pterodactyl Panel
         run: |
-          cd /tmp/panel
           cp .env.example .env
           docker-compose build --pull
           docker-compose up -d
